// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "github_com_noircode_backend_internal_domain_noircode_model.DecodeResult": {
                "properties": {
                    "confidence": {
                        "type": "number"
                    },
                    "cross_check": {
                        "type": "boolean"
                    },
                    "failed_stage": {
                        "type": "string"
                    },
                    "grid_erasures": {
                        "type": "integer"
                    },
                    "motif_erasures": {
                        "type": "integer"
                    },
                    "ok": {
                        "type": "boolean"
                    },
                    "rotation": {
                        "type": "integer"
                    },
                    "text": {
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "internal_domain_noircode_adapter_fiber.encodeReq": {
                "properties": {
                    "adaptive": {
                        "description": "Adaptive defaults to true (smaller panel for short text). Send false to\nforce the full fixed grid.",
                        "type": "boolean"
                    },
                    "caption": {
                        "description": "Caption stamped under the panel. Omit to use the server default; send an\nempty string to disable the caption.",
                        "type": "string"
                    },
                    "hatch_data": {
                        "type": "boolean"
                    },
                    "style": {
                        "type": "boolean"
                    },
                    "text": {
                        "type": "string"
                    }
                },
                "type": "object"
            }
        }
    },
    "info": {
        "contact": {
            "name": "Sunkek"
        },
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/decode": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "title": "image",
                                "type": "file"
                            }
                        },
                        "multipart/form-data": {
                            "schema": {
                                "type": "object"
                            }
                        }
                    },
                    "description": "panel image (PNG/JPEG)",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/github_com_noircode_backend_internal_domain_noircode_model.DecodeResult"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Decode a NoiR Code panel image to text",
                "tags": [
                    "noircode"
                ]
            }
        },
        "/encode": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "oneOf": [
                                    {
                                        "type": "object"
                                    },
                                    {
                                        "$ref": "#/components/schemas/internal_domain_noircode_adapter_fiber.encodeReq",
                                        "summary": "body",
                                        "description": "encode options"
                                    }
                                ]
                            }
                        }
                    },
                    "description": "encode options",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "image/png": {
                                "schema": {
                                    "type": "file"
                                }
                            }
                        },
                        "description": "OK"
                    }
                },
                "summary": "Encode text into a NoiR Code panel",
                "tags": [
                    "noircode"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/api/v1"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Title:            "NoiR Code API",
	Description:      "Encode text into a NoiR Code panel and decode panels back to text.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
